#######
# Compiled from /ac_lib/functions/create.mcscript
# to .//ac_lib/functions/create/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ac_lib:create/craftingtable/detect
