#######
# Compiled from data/ac_lib/functions/tick.mcscript
# to .//data/ac_lib/functions/tick.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ac_lib:crafting/main
function ac_lib:create/main
function ac_lib:remove/main
function ac_lib:example